package com.goviet.keyboard.engine

object TokenValidMap {

    private const val TABLE_BITS = 14
    private const val TABLE_SIZE = 1 shl TABLE_BITS
    private const val TABLE_MASK = TABLE_SIZE - 1
    private val _table = LongArray(TABLE_SIZE)

    private fun packKey(s: String): Long {
        var key = s.length.toLong() shl 55
        for (i in s.indices) {
            val idx = s[i].code - 'a'.code
            if (idx < 0 || idx >= 26) return -1L
            key = key or (idx.toLong() shl (50 - 5 * i))
        }
        return key
    }

    private fun hash(key: Long): Int =
        ((key * -0x61c88647L) xor (key ushr 32)).toInt() and TABLE_MASK

    private fun insert(key: Long) {
        if (key < 0) return
        var slot = hash(key)
        while (true) {
            if (_table[slot] == key) return
            if (_table[slot] == 0L) { _table[slot] = key; return }
            slot = (slot + 1) and TABLE_MASK
        }
    }

    fun isValidPrefix(s: String): Boolean {
        val key = packKey(s)
        if (key < 0) return false
        var slot = hash(key)
        while (true) {
            if (_table[slot] == key) return true
            if (_table[slot] == 0L) return false
            slot = (slot + 1) and TABLE_MASK
        }
    }

    fun isDisplayPrefixValid(display: String): Boolean {
        if (display.isEmpty()) return true
        val ascii = stripDiacritics(display)
        if (ascii.isEmpty()) return true
        return isValidPrefix(ascii)
    }

    private fun stripDiacritics(text: String): String {
        val sb = StringBuilder(text.length)
        for (c in text) {
            val base = VIET_TO_ASCII[c.code]
            if (base != null) { sb.append(base); continue }
            if (c.code in 0x61..0x7A) { sb.append(c); continue }
            if (c.code in 0x41..0x5A) { sb.append((c.code + 32).toChar()); continue }
            val decomposed = java.text.Normalizer.normalize(c.toString(), java.text.Normalizer.Form.NFD)
            for (ch in decomposed) {
                if (ch.code in 0x61..0x7A) { sb.append(ch); break }
                if (ch.code in 0x41..0x5A) { sb.append((ch.code + 32).toChar()); break }
            }
        }
        return sb.toString()
    }

    private val VIET_TO_ASCII: Array<Char?> = arrayOfNulls<Char?>(0x1EF9 + 1).also { arr ->
        val m = mapOf(
            'ă' to 'a', 'â' to 'a', 'đ' to 'd', 'ê' to 'e', 'ô' to 'o',
            'ơ' to 'o', 'ư' to 'u', 'á' to 'a', 'à' to 'a', 'ả' to 'a',
            'ã' to 'a', 'ạ' to 'a', 'ắ' to 'a', 'ằ' to 'a', 'ẳ' to 'a',
            'ẵ' to 'a', 'ặ' to 'a', 'ấ' to 'a', 'ầ' to 'a', 'ẩ' to 'a',
            'ẫ' to 'a', 'ậ' to 'a', 'é' to 'e', 'è' to 'e', 'ẻ' to 'e',
            'ẽ' to 'e', 'ẹ' to 'e', 'ế' to 'e', 'ề' to 'e', 'ể' to 'e',
            'ễ' to 'e', 'ệ' to 'e', 'í' to 'i', 'ì' to 'i', 'ỉ' to 'i',
            'ĩ' to 'i', 'ị' to 'i', 'ó' to 'o', 'ò' to 'o', 'ỏ' to 'o',
            'õ' to 'o', 'ọ' to 'o', 'ố' to 'o', 'ồ' to 'o', 'ổ' to 'o',
            'ỗ' to 'o', 'ộ' to 'o', 'ớ' to 'o', 'ờ' to 'o', 'ở' to 'o',
            'ỡ' to 'o', 'ợ' to 'o', 'ú' to 'u', 'ù' to 'u', 'ủ' to 'u',
            'ũ' to 'u', 'ụ' to 'u', 'ứ' to 'u', 'ừ' to 'u', 'ử' to 'u',
            'ữ' to 'u', 'ự' to 'u', 'ý' to 'y', 'ỳ' to 'y', 'ỷ' to 'y',
            'ỹ' to 'y', 'ỵ' to 'y',
        )
        for ((k, v) in m) arr[k.code] = v
    }

    // Auto-generated: 2705 prefixes from 17974 syllables
    private val EMBEDDED = arrayOf(
        "a", "ac", "ach", "ai", "am", "an", "ang", "anh",
        "ao", "ap", "at", "au", "ay", "b", "ba", "bac",
        "bach", "bai", "bam", "ban", "bang", "banh", "bao", "bap",
        "bat", "bau", "bay", "be", "bec", "bech", "bem", "ben",
        "beng", "benh", "beo", "bep", "bet", "beu", "bi", "bia",
        "bic", "bich", "bie", "biec", "biem", "bien", "bieng", "biep",
        "biet", "bieu", "bim", "bin", "binh", "bip", "bit", "biu",
        "bo", "boa", "boac", "boach", "boai", "boam", "boan", "boang",
        "boanh", "boao", "boap", "boat", "boay", "boc", "boe", "boem",
        "boen", "boeo", "boet", "boi", "bom", "bon", "bong", "boo",
        "booc", "boon", "boong", "bop", "bot", "bu", "bua", "buan",
        "buang", "buat", "buay", "buc", "bue", "buec", "buech", "buen",
        "buenh", "bui", "bum", "bun", "bung", "buo", "buoc", "buoi",
        "buom", "buon", "buong", "buop", "buot", "buou", "bup", "but",
        "buu", "buy", "buya", "buyc", "buych", "buye", "buyen", "buyet",
        "buyn", "buynh", "buyp", "buyt", "buyu", "by", "c", "ca",
        "cac", "cach", "cai", "cam", "can", "cang", "canh", "cao",
        "cap", "cat", "cau", "cay", "ch", "cha", "chac", "chach",
        "chai", "cham", "chan", "chang", "chanh", "chao", "chap", "chat",
        "chau", "chay", "che", "chec", "chech", "chem", "chen", "cheng",
        "chenh", "cheo", "chep", "chet", "cheu", "chi", "chia", "chic",
        "chich", "chie", "chiec", "chiem", "chien", "chieng", "chiep", "chiet",
        "chieu", "chim", "chin", "chinh", "chip", "chit", "chiu", "cho",
        "choa", "choac", "choach", "choai", "choam", "choan", "choang", "choanh",
        "choao", "choap", "choat", "choay", "choc", "choe", "choem", "choen",
        "choeo", "choet", "choi", "chom", "chon", "chong", "choo", "chooc",
        "choon", "choong", "chop", "chot", "chu", "chua", "chuan", "chuang",
        "chuat", "chuay", "chuc", "chue", "chuec", "chuech", "chuen", "chuenh",
        "chui", "chum", "chun", "chung", "chuo", "chuoc", "chuoi", "chuom",
        "chuon", "chuong", "chuop", "chuot", "chuou", "chup", "chut", "chuu",
        "chuy", "chuya", "chuyc", "chuych", "chuye", "chuyen", "chuyet", "chuyn",
        "chuynh", "chuyp", "chuyt", "chuyu", "chy", "co", "coa", "coac",
        "coach", "coai", "coam", "coan", "coang", "coanh", "coao", "coap",
        "coat", "coay", "coc", "coe", "coem", "coen", "coeo", "coet",
        "coi", "com", "con", "cong", "coo", "cooc", "coon", "coong",
        "cop", "cot", "cu", "cua", "cuan", "cuang", "cuat", "cuay",
        "cuc", "cue", "cuec", "cuech", "cuen", "cuenh", "cui", "cum",
        "cun", "cung", "cuo", "cuoc", "cuoi", "cuom", "cuon", "cuong",
        "cuop", "cuot", "cuou", "cup", "cut", "cuu", "cuy", "cuya",
        "cuyc", "cuych", "cuye", "cuyen", "cuyet", "cuyn", "cuynh", "cuyp",
        "cuyt", "cuyu", "d", "da", "dac", "dach", "dai", "dam",
        "dan", "dang", "danh", "dao", "dap", "dat", "dau", "day",
        "de", "dec", "dech", "dem", "den", "deng", "denh", "deo",
        "dep", "det", "deu", "di", "dia", "dic", "dich", "die",
        "diec", "diem", "dien", "dieng", "diep", "diet", "dieu", "dim",
        "din", "dinh", "dip", "dit", "diu", "do", "doa", "doac",
        "doach", "doai", "doam", "doan", "doang", "doanh", "doao", "doap",
        "doat", "doay", "doc", "doe", "doem", "doen", "doeo", "doet",
        "doi", "dom", "don", "dong", "doo", "dooc", "doon", "doong",
        "dop", "dot", "du", "dua", "duan", "duang", "duat", "duay",
        "duc", "due", "duec", "duech", "duen", "duenh", "dui", "dum",
        "dun", "dung", "duo", "duoc", "duoi", "duom", "duon", "duong",
        "duop", "duot", "duou", "dup", "dut", "duu", "duy", "duya",
        "duyc", "duych", "duye", "duyen", "duyet", "duyn", "duynh", "duyp",
        "duyt", "duyu", "dy", "e", "ec", "ech", "em", "en",
        "eng", "enh", "eo", "ep", "et", "eu", "g", "ga",
        "gac", "gach", "gai", "gam", "gan", "gang", "ganh", "gao",
        "gap", "gat", "gau", "gay", "gh", "ghe", "ghec", "ghech",
        "ghem", "ghen", "gheng", "ghenh", "gheo", "ghep", "ghet", "gheu",
        "ghi", "ghia", "ghic", "ghich", "ghie", "ghiec", "ghiem", "ghien",
        "ghieng", "ghiep", "ghiet", "ghieu", "ghim", "ghin", "ghinh", "ghip",
        "ghit", "ghiu", "ghy", "gi", "gia", "giac", "giach", "giai",
        "giam", "gian", "giang", "gianh", "giao", "giap", "giat", "giau",
        "giay", "gic", "gich", "gie", "giec", "giech", "giem", "gien",
        "gieng", "gienh", "gieo", "giep", "giet", "gieu", "gim", "gin",
        "ginh", "gio", "gioa", "gioac", "gioach", "gioai", "gioam", "gioan",
        "gioang", "gioanh", "gioao", "gioap", "gioat", "gioay", "gioc", "gioe",
        "gioem", "gioen", "gioeo", "gioet", "gioi", "giom", "gion", "giong",
        "gioo", "giooc", "gioon", "gioong", "giop", "giot", "gip", "git",
        "giu", "giua", "giuan", "giuang", "giuat", "giuay", "giuc", "giue",
        "giuec", "giuech", "giuen", "giuenh", "giui", "gium", "giun", "giung",
        "giuo", "giuoc", "giuoi", "giuom", "giuon", "giuong", "giuop", "giuot",
        "giuou", "giup", "giut", "giuu", "giuy", "giuya", "giuyc", "giuych",
        "giuye", "giuyen", "giuyet", "giuyn", "giuynh", "giuyp", "giuyt", "giuyu",
        "giy", "go", "goa", "goac", "goach", "goai", "goam", "goan",
        "goang", "goanh", "goao", "goap", "goat", "goay", "goc", "goe",
        "goem", "goen", "goeo", "goet", "goi", "gom", "gon", "gong",
        "goo", "gooc", "goon", "goong", "gop", "got", "gu", "gua",
        "guan", "guang", "guat", "guay", "guc", "gue", "guec", "guech",
        "guen", "guenh", "gui", "gum", "gun", "gung", "guo", "guoc",
        "guoi", "guom", "guon", "guong", "guop", "guot", "guou", "gup",
        "gut", "guu", "guy", "guya", "guyc", "guych", "guye", "guyen",
        "guyet", "guyn", "guynh", "guyp", "guyt", "guyu", "h", "ha",
        "hac", "hach", "hai", "ham", "han", "hang", "hanh", "hao",
        "hap", "hat", "hau", "hay", "he", "hec", "hech", "hem",
        "hen", "heng", "henh", "heo", "hep", "het", "heu", "hi",
        "hia", "hic", "hich", "hie", "hiec", "hiem", "hien", "hieng",
        "hiep", "hiet", "hieu", "him", "hin", "hinh", "hip", "hit",
        "hiu", "ho", "hoa", "hoac", "hoach", "hoai", "hoam", "hoan",
        "hoang", "hoanh", "hoao", "hoap", "hoat", "hoay", "hoc", "hoe",
        "hoem", "hoen", "hoeo", "hoet", "hoi", "hom", "hon", "hong",
        "hoo", "hooc", "hoon", "hoong", "hop", "hot", "hu", "hua",
        "huan", "huang", "huat", "huay", "huc", "hue", "huec", "huech",
        "huen", "huenh", "hui", "hum", "hun", "hung", "huo", "huoc",
        "huoi", "huom", "huon", "huong", "huop", "huot", "huou", "hup",
        "hut", "huu", "huy", "huya", "huyc", "huych", "huye", "huyen",
        "huyet", "huyn", "huynh", "huyp", "huyt", "huyu", "hy", "i",
        "ia", "ic", "ich", "ie", "iec", "iem", "ien", "ieng",
        "iep", "iet", "ieu", "im", "in", "inh", "ip", "it",
        "iu", "k", "ke", "kec", "kech", "kem", "ken", "keng",
        "kenh", "keo", "kep", "ket", "keu", "kh", "kha", "khac",
        "khach", "khai", "kham", "khan", "khang", "khanh", "khao", "khap",
        "khat", "khau", "khay", "khe", "khec", "khech", "khem", "khen",
        "kheng", "khenh", "kheo", "khep", "khet", "kheu", "khi", "khia",
        "khic", "khich", "khie", "khiec", "khiem", "khien", "khieng", "khiep",
        "khiet", "khieu", "khim", "khin", "khinh", "khip", "khit", "khiu",
        "kho", "khoa", "khoac", "khoach", "khoai", "khoam", "khoan", "khoang",
        "khoanh", "khoao", "khoap", "khoat", "khoay", "khoc", "khoe", "khoem",
        "khoen", "khoeo", "khoet", "khoi", "khom", "khon", "khong", "khoo",
        "khooc", "khoon", "khoong", "khop", "khot", "khu", "khua", "khuan",
        "khuang", "khuat", "khuay", "khuc", "khue", "khuec", "khuech", "khuen",
        "khuenh", "khui", "khum", "khun", "khung", "khuo", "khuoc", "khuoi",
        "khuom", "khuon", "khuong", "khuop", "khuot", "khuou", "khup", "khut",
        "khuu", "khuy", "khuya", "khuyc", "khuych", "khuye", "khuyen", "khuyet",
        "khuyn", "khuynh", "khuyp", "khuyt", "khuyu", "khy", "ki", "kia",
        "kic", "kich", "kie", "kiec", "kiem", "kien", "kieng", "kiep",
        "kiet", "kieu", "kim", "kin", "kinh", "kip", "kit", "kiu",
        "ky", "l", "la", "lac", "lach", "lai", "lam", "lan",
        "lang", "lanh", "lao", "lap", "lat", "lau", "lay", "le",
        "lec", "lech", "lem", "len", "leng", "lenh", "leo", "lep",
        "let", "leu", "li", "lia", "lic", "lich", "lie", "liec",
        "liem", "lien", "lieng", "liep", "liet", "lieu", "lim", "lin",
        "linh", "lip", "lit", "liu", "lo", "loa", "loac", "loach",
        "loai", "loam", "loan", "loang", "loanh", "loao", "loap", "loat",
        "loay", "loc", "loe", "loem", "loen", "loeo", "loet", "loi",
        "lom", "lon", "long", "loo", "looc", "loon", "loong", "lop",
        "lot", "lu", "lua", "luan", "luang", "luat", "luay", "luc",
        "lue", "luec", "luech", "luen", "luenh", "lui", "lum", "lun",
        "lung", "luo", "luoc", "luoi", "luom", "luon", "luong", "luop",
        "luot", "luou", "lup", "lut", "luu", "luy", "luya", "luyc",
        "luych", "luye", "luyen", "luyet", "luyn", "luynh", "luyp", "luyt",
        "luyu", "ly", "m", "ma", "mac", "mach", "mai", "mam",
        "man", "mang", "manh", "mao", "map", "mat", "mau", "may",
        "me", "mec", "mech", "mem", "men", "meng", "menh", "meo",
        "mep", "met", "meu", "mi", "mia", "mic", "mich", "mie",
        "miec", "miem", "mien", "mieng", "miep", "miet", "mieu", "mim",
        "min", "minh", "mip", "mit", "miu", "mo", "moa", "moac",
        "moach", "moai", "moam", "moan", "moang", "moanh", "moao", "moap",
        "moat", "moay", "moc", "moe", "moem", "moen", "moeo", "moet",
        "moi", "mom", "mon", "mong", "moo", "mooc", "moon", "moong",
        "mop", "mot", "mu", "mua", "muan", "muang", "muat", "muay",
        "muc", "mue", "muec", "muech", "muen", "muenh", "mui", "mum",
        "mun", "mung", "muo", "muoc", "muoi", "muom", "muon", "muong",
        "muop", "muot", "muou", "mup", "mut", "muu", "muy", "muya",
        "muyc", "muych", "muye", "muyen", "muyet", "muyn", "muynh", "muyp",
        "muyt", "muyu", "my", "n", "na", "nac", "nach", "nai",
        "nam", "nan", "nang", "nanh", "nao", "nap", "nat", "nau",
        "nay", "ne", "nec", "nech", "nem", "nen", "neng", "nenh",
        "neo", "nep", "net", "neu", "ng", "nga", "ngac", "ngach",
        "ngai", "ngam", "ngan", "ngang", "nganh", "ngao", "ngap", "ngat",
        "ngau", "ngay", "ngh", "nghe", "nghec", "nghech", "nghem", "nghen",
        "ngheng", "nghenh", "ngheo", "nghep", "nghet", "ngheu", "nghi", "nghia",
        "nghic", "nghich", "nghie", "nghiec", "nghiem", "nghien", "nghieng", "nghiep",
        "nghiet", "nghieu", "nghim", "nghin", "nghinh", "nghip", "nghit", "nghiu",
        "nghy", "ngo", "ngoa", "ngoac", "ngoach", "ngoai", "ngoam", "ngoan",
        "ngoang", "ngoanh", "ngoao", "ngoap", "ngoat", "ngoay", "ngoc", "ngoe",
        "ngoem", "ngoen", "ngoeo", "ngoet", "ngoi", "ngom", "ngon", "ngong",
        "ngoo", "ngooc", "ngoon", "ngoong", "ngop", "ngot", "ngu", "ngua",
        "nguan", "nguang", "nguat", "nguay", "nguc", "ngue", "nguec", "nguech",
        "nguen", "nguenh", "ngui", "ngum", "ngun", "ngung", "nguo", "nguoc",
        "nguoi", "nguom", "nguon", "nguong", "nguop", "nguot", "nguou", "ngup",
        "ngut", "nguu", "nguy", "nguya", "nguyc", "nguych", "nguye", "nguyen",
        "nguyet", "nguyn", "nguynh", "nguyp", "nguyt", "nguyu", "nh", "nha",
        "nhac", "nhach", "nhai", "nham", "nhan", "nhang", "nhanh", "nhao",
        "nhap", "nhat", "nhau", "nhay", "nhe", "nhec", "nhech", "nhem",
        "nhen", "nheng", "nhenh", "nheo", "nhep", "nhet", "nheu", "nhi",
        "nhia", "nhic", "nhich", "nhie", "nhiec", "nhiem", "nhien", "nhieng",
        "nhiep", "nhiet", "nhieu", "nhim", "nhin", "nhinh", "nhip", "nhit",
        "nhiu", "nho", "nhoa", "nhoac", "nhoach", "nhoai", "nhoam", "nhoan",
        "nhoang", "nhoanh", "nhoao", "nhoap", "nhoat", "nhoay", "nhoc", "nhoe",
        "nhoem", "nhoen", "nhoeo", "nhoet", "nhoi", "nhom", "nhon", "nhong",
        "nhoo", "nhooc", "nhoon", "nhoong", "nhop", "nhot", "nhu", "nhua",
        "nhuan", "nhuang", "nhuat", "nhuay", "nhuc", "nhue", "nhuec", "nhuech",
        "nhuen", "nhuenh", "nhui", "nhum", "nhun", "nhung", "nhuo", "nhuoc",
        "nhuoi", "nhuom", "nhuon", "nhuong", "nhuop", "nhuot", "nhuou", "nhup",
        "nhut", "nhuu", "nhuy", "nhuya", "nhuyc", "nhuych", "nhuye", "nhuyen",
        "nhuyet", "nhuyn", "nhuynh", "nhuyp", "nhuyt", "nhuyu", "nhy", "ni",
        "nia", "nic", "nich", "nie", "niec", "niem", "nien", "nieng",
        "niep", "niet", "nieu", "nim", "nin", "ninh", "nip", "nit",
        "niu", "no", "noa", "noac", "noach", "noai", "noam", "noan",
        "noang", "noanh", "noao", "noap", "noat", "noay", "noc", "noe",
        "noem", "noen", "noeo", "noet", "noi", "nom", "non", "nong",
        "noo", "nooc", "noon", "noong", "nop", "not", "nu", "nua",
        "nuan", "nuang", "nuat", "nuay", "nuc", "nue", "nuec", "nuech",
        "nuen", "nuenh", "nui", "num", "nun", "nung", "nuo", "nuoc",
        "nuoi", "nuom", "nuon", "nuong", "nuop", "nuot", "nuou", "nup",
        "nut", "nuu", "nuy", "nuya", "nuyc", "nuych", "nuye", "nuyen",
        "nuyet", "nuyn", "nuynh", "nuyp", "nuyt", "nuyu", "ny", "o",
        "oa", "oac", "oach", "oai", "oam", "oan", "oang", "oanh",
        "oao", "oap", "oat", "oay", "oc", "oe", "oem", "oen",
        "oeo", "oet", "oi", "om", "on", "ong", "oo", "ooc",
        "oon", "oong", "op", "ot", "p", "pa", "pac", "pach",
        "pai", "pam", "pan", "pang", "panh", "pao", "pap", "pat",
        "pau", "pay", "pe", "pec", "pech", "pem", "pen", "peng",
        "penh", "peo", "pep", "pet", "peu", "ph", "pha", "phac",
        "phach", "phai", "pham", "phan", "phang", "phanh", "phao", "phap",
        "phat", "phau", "phay", "phe", "phec", "phech", "phem", "phen",
        "pheng", "phenh", "pheo", "phep", "phet", "pheu", "phi", "phia",
        "phic", "phich", "phie", "phiec", "phiem", "phien", "phieng", "phiep",
        "phiet", "phieu", "phim", "phin", "phinh", "phip", "phit", "phiu",
        "pho", "phoa", "phoac", "phoach", "phoai", "phoam", "phoan", "phoang",
        "phoanh", "phoao", "phoap", "phoat", "phoay", "phoc", "phoe", "phoem",
        "phoen", "phoeo", "phoet", "phoi", "phom", "phon", "phong", "phoo",
        "phooc", "phoon", "phoong", "phop", "phot", "phu", "phua", "phuan",
        "phuang", "phuat", "phuay", "phuc", "phue", "phuec", "phuech", "phuen",
        "phuenh", "phui", "phum", "phun", "phung", "phuo", "phuoc", "phuoi",
        "phuom", "phuon", "phuong", "phuop", "phuot", "phuou", "phup", "phut",
        "phuu", "phuy", "phuya", "phuyc", "phuych", "phuye", "phuyen", "phuyet",
        "phuyn", "phuynh", "phuyp", "phuyt", "phuyu", "phy", "pi", "pia",
        "pic", "pich", "pie", "piec", "piem", "pien", "pieng", "piep",
        "piet", "pieu", "pim", "pin", "pinh", "pip", "pit", "piu",
        "po", "poa", "poac", "poach", "poai", "poam", "poan", "poang",
        "poanh", "poao", "poap", "poat", "poay", "poc", "poe", "poem",
        "poen", "poeo", "poet", "poi", "pom", "pon", "pong", "poo",
        "pooc", "poon", "poong", "pop", "pot", "pu", "pua", "puan",
        "puang", "puat", "puay", "puc", "pue", "puec", "puech", "puen",
        "puenh", "pui", "pum", "pun", "pung", "puo", "puoc", "puoi",
        "puom", "puon", "puong", "puop", "puot", "puou", "pup", "put",
        "puu", "puy", "puya", "puyc", "puych", "puye", "puyen", "puyet",
        "puyn", "puynh", "puyp", "puyt", "puyu", "py", "q", "qu",
        "qua", "quac", "quach", "quai", "quam", "quan", "quang", "quanh",
        "quao", "quap", "quat", "quau", "quay", "quc", "que", "quec",
        "quech", "quem", "quen", "queng", "quenh", "queo", "quep", "quet",
        "queu", "qui", "quia", "quic", "quich", "quie", "quiec", "quiem",
        "quien", "quieng", "quiep", "quiet", "quieu", "quim", "quin", "quinh",
        "quip", "quit", "quiu", "qum", "qun", "qung", "quo", "quoa",
        "quoac", "quoach", "quoai", "quoam", "quoan", "quoang", "quoanh", "quoao",
        "quoap", "quoat", "quoay", "quoc", "quoe", "quoem", "quoen", "quoeo",
        "quoet", "quoi", "quom", "quon", "quong", "quoo", "quooc", "quoon",
        "quoong", "quop", "quot", "qup", "qut", "quu", "quua", "quuc",
        "quui", "quum", "quun", "quung", "quuo", "quuoc", "quuoi", "quuom",
        "quuon", "quuong", "quuop", "quuot", "quuou", "quut", "quuu", "quy",
        "quya", "quyc", "quych", "quye", "quyen", "quyet", "quyn", "quynh",
        "quyp", "quyt", "quyu", "r", "ra", "rac", "rach", "rai",
        "ram", "ran", "rang", "ranh", "rao", "rap", "rat", "rau",
        "ray", "re", "rec", "rech", "rem", "ren", "reng", "renh",
        "reo", "rep", "ret", "reu", "ri", "ria", "ric", "rich",
        "rie", "riec", "riem", "rien", "rieng", "riep", "riet", "rieu",
        "rim", "rin", "rinh", "rip", "rit", "riu", "ro", "roa",
        "roac", "roach", "roai", "roam", "roan", "roang", "roanh", "roao",
        "roap", "roat", "roay", "roc", "roe", "roem", "roen", "roeo",
        "roet", "roi", "rom", "ron", "rong", "roo", "rooc", "roon",
        "roong", "rop", "rot", "ru", "rua", "ruan", "ruang", "ruat",
        "ruay", "ruc", "rue", "ruec", "ruech", "ruen", "ruenh", "rui",
        "rum", "run", "rung", "ruo", "ruoc", "ruoi", "ruom", "ruon",
        "ruong", "ruop", "ruot", "ruou", "rup", "rut", "ruu", "ruy",
        "ruya", "ruyc", "ruych", "ruye", "ruyen", "ruyet", "ruyn", "ruynh",
        "ruyp", "ruyt", "ruyu", "ry", "s", "sa", "sac", "sach",
        "sai", "sam", "san", "sang", "sanh", "sao", "sap", "sat",
        "sau", "say", "se", "sec", "sech", "sem", "sen", "seng",
        "senh", "seo", "sep", "set", "seu", "si", "sia", "sic",
        "sich", "sie", "siec", "siem", "sien", "sieng", "siep", "siet",
        "sieu", "sim", "sin", "sinh", "sip", "sit", "siu", "so",
        "soa", "soac", "soach", "soai", "soam", "soan", "soang", "soanh",
        "soao", "soap", "soat", "soay", "soc", "soe", "soem", "soen",
        "soeo", "soet", "soi", "som", "son", "song", "soo", "sooc",
        "soon", "soong", "sop", "sot", "su", "sua", "suan", "suang",
        "suat", "suay", "suc", "sue", "suec", "suech", "suen", "suenh",
        "sui", "sum", "sun", "sung", "suo", "suoc", "suoi", "suom",
        "suon", "suong", "suop", "suot", "suou", "sup", "sut", "suu",
        "suy", "suya", "suyc", "suych", "suye", "suyen", "suyet", "suyn",
        "suynh", "suyp", "suyt", "suyu", "sy", "t", "ta", "tac",
        "tach", "tai", "tam", "tan", "tang", "tanh", "tao", "tap",
        "tat", "tau", "tay", "te", "tec", "tech", "tem", "ten",
        "teng", "tenh", "teo", "tep", "tet", "teu", "th", "tha",
        "thac", "thach", "thai", "tham", "than", "thang", "thanh", "thao",
        "thap", "that", "thau", "thay", "the", "thec", "thech", "them",
        "then", "theng", "thenh", "theo", "thep", "thet", "theu", "thi",
        "thia", "thic", "thich", "thie", "thiec", "thiem", "thien", "thieng",
        "thiep", "thiet", "thieu", "thim", "thin", "thinh", "thip", "thit",
        "thiu", "tho", "thoa", "thoac", "thoach", "thoai", "thoam", "thoan",
        "thoang", "thoanh", "thoao", "thoap", "thoat", "thoay", "thoc", "thoe",
        "thoem", "thoen", "thoeo", "thoet", "thoi", "thom", "thon", "thong",
        "thoo", "thooc", "thoon", "thoong", "thop", "thot", "thu", "thua",
        "thuan", "thuang", "thuat", "thuay", "thuc", "thue", "thuec", "thuech",
        "thuen", "thuenh", "thui", "thum", "thun", "thung", "thuo", "thuoc",
        "thuoi", "thuom", "thuon", "thuong", "thuop", "thuot", "thuou", "thup",
        "thut", "thuu", "thuy", "thuya", "thuyc", "thuych", "thuye", "thuyen",
        "thuyet", "thuyn", "thuynh", "thuyp", "thuyt", "thuyu", "thy", "ti",
        "tia", "tic", "tich", "tie", "tiec", "tiem", "tien", "tieng",
        "tiep", "tiet", "tieu", "tim", "tin", "tinh", "tip", "tit",
        "tiu", "to", "toa", "toac", "toach", "toai", "toam", "toan",
        "toang", "toanh", "toao", "toap", "toat", "toay", "toc", "toe",
        "toem", "toen", "toeo", "toet", "toi", "tom", "ton", "tong",
        "too", "tooc", "toon", "toong", "top", "tot", "tr", "tra",
        "trac", "trach", "trai", "tram", "tran", "trang", "tranh", "trao",
        "trap", "trat", "trau", "tray", "tre", "trec", "trech", "trem",
        "tren", "treng", "trenh", "treo", "trep", "tret", "treu", "tri",
        "tria", "tric", "trich", "trie", "triec", "triem", "trien", "trieng",
        "triep", "triet", "trieu", "trim", "trin", "trinh", "trip", "trit",
        "triu", "tro", "troa", "troac", "troach", "troai", "troam", "troan",
        "troang", "troanh", "troao", "troap", "troat", "troay", "troc", "troe",
        "troem", "troen", "troeo", "troet", "troi", "trom", "tron", "trong",
        "troo", "trooc", "troon", "troong", "trop", "trot", "tru", "trua",
        "truan", "truang", "truat", "truay", "truc", "true", "truec", "truech",
        "truen", "truenh", "trui", "trum", "trun", "trung", "truo", "truoc",
        "truoi", "truom", "truon", "truong", "truop", "truot", "truou", "trup",
        "trut", "truu", "truy", "truya", "truyc", "truych", "truye", "truyen",
        "truyet", "truyn", "truynh", "truyp", "truyt", "truyu", "try", "tu",
        "tua", "tuan", "tuang", "tuat", "tuay", "tuc", "tue", "tuec",
        "tuech", "tuen", "tuenh", "tui", "tum", "tun", "tung", "tuo",
        "tuoc", "tuoi", "tuom", "tuon", "tuong", "tuop", "tuot", "tuou",
        "tup", "tut", "tuu", "tuy", "tuya", "tuyc", "tuych", "tuye",
        "tuyen", "tuyet", "tuyn", "tuynh", "tuyp", "tuyt", "tuyu", "ty",
        "u", "ua", "uan", "uang", "uat", "uay", "uc", "ue",
        "uec", "uech", "uen", "uenh", "ui", "um", "un", "ung",
        "uo", "uoc", "uoi", "uom", "uon", "uong", "uop", "uot",
        "uou", "up", "ut", "uu", "uy", "uya", "uyc", "uych",
        "uye", "uyen", "uyet", "uyn", "uynh", "uyp", "uyt", "uyu",
        "v", "va", "vac", "vach", "vai", "vam", "van", "vang",
        "vanh", "vao", "vap", "vat", "vau", "vay", "ve", "vec",
        "vech", "vem", "ven", "veng", "venh", "veo", "vep", "vet",
        "veu", "vi", "via", "vic", "vich", "vie", "viec", "viem",
        "vien", "vieng", "viep", "viet", "vieu", "vim", "vin", "vinh",
        "vip", "vit", "viu", "vo", "voa", "voac", "voach", "voai",
        "voam", "voan", "voang", "voanh", "voao", "voap", "voat", "voay",
        "voc", "voe", "voem", "voen", "voeo", "voet", "voi", "vom",
        "von", "vong", "voo", "vooc", "voon", "voong", "vop", "vot",
        "vu", "vua", "vuan", "vuang", "vuat", "vuay", "vuc", "vue",
        "vuec", "vuech", "vuen", "vuenh", "vui", "vum", "vun", "vung",
        "vuo", "vuoc", "vuoi", "vuom", "vuon", "vuong", "vuop", "vuot",
        "vuou", "vup", "vut", "vuu", "vuy", "vuya", "vuyc", "vuych",
        "vuye", "vuyen", "vuyet", "vuyn", "vuynh", "vuyp", "vuyt", "vuyu",
        "vy", "x", "xa", "xac", "xach", "xai", "xam", "xan",
        "xang", "xanh", "xao", "xap", "xat", "xau", "xay", "xe",
        "xec", "xech", "xem", "xen", "xeng", "xenh", "xeo", "xep",
        "xet", "xeu", "xi", "xia", "xic", "xich", "xie", "xiec",
        "xiem", "xien", "xieng", "xiep", "xiet", "xieu", "xim", "xin",
        "xinh", "xip", "xit", "xiu", "xo", "xoa", "xoac", "xoach",
        "xoai", "xoam", "xoan", "xoang", "xoanh", "xoao", "xoap", "xoat",
        "xoay", "xoc", "xoe", "xoem", "xoen", "xoeo", "xoet", "xoi",
        "xom", "xon", "xong", "xoo", "xooc", "xoon", "xoong", "xop",
        "xot", "xu", "xua", "xuan", "xuang", "xuat", "xuay", "xuc",
        "xue", "xuec", "xuech", "xuen", "xuenh", "xui", "xum", "xun",
        "xung", "xuo", "xuoc", "xuoi", "xuom", "xuon", "xuong", "xuop",
        "xuot", "xuou", "xup", "xut", "xuu", "xuy", "xuya", "xuyc",
        "xuych", "xuye", "xuyen", "xuyet", "xuyn", "xuynh", "xuyp", "xuyt",
        "xuyu", "xy", "y", "ye", "yem", "yen", "yeng", "yet",
        "yeu",
    )

    init {
        for (prefix in EMBEDDED) insert(packKey(prefix))
    }
}
