package com.goviet.keyboard.ui

val secondaryKeyMap = mapOf(
    "q" to "@", "w" to "#", "e" to "₫", "r" to "_", "t" to "&",
    "y" to "–", "u" to "±", "i" to "×", "o" to "÷",
    "p" to "*", "a" to "°", "s" to "?", "d" to "\"",
    "f" to "'", "g" to ":", "h" to ";",
    "j" to "/", "k" to "~", "l" to "\\",
    "z" to "%", "x" to "<", "c" to ">",
    "v" to "[", "b" to "]", "n" to "{", "m" to "}"
)

val longPressSymbolMap = mapOf(
    // Vowels — single symbols from page 2 (symbol pages handle rest)
    "e" to listOf("₫", "$", "€"),
    "y" to listOf("–", "—"),
    "u" to listOf("±", "+"),
    "i" to listOf("×", "•"),
    "o" to listOf("÷", "≠"),
    "a" to listOf("°", "℃"),
    // Consonants — common daily symbols
    "q" to listOf("@"),
    "w" to listOf("#"),
    "r" to listOf("_", "—"),
    "t" to listOf("&", "§"),
    "p" to listOf("*"),
    "s" to listOf("?", "¿"),
    "d" to listOf("\"", "“", "”", "„"),
    "f" to listOf("'", "`"),
    "g" to listOf(":", "："),
    "h" to listOf(";", "；"),
    "j" to listOf("/", "\\", "|"),
    "k" to listOf("~", "`"),
    "l" to listOf("\\"),
    "z" to listOf("%", "‰"),
    "x" to listOf("<", "«"),
    "c" to listOf(">", "»"),
    "b" to listOf("]", "⟩"),
    "m" to listOf("}")
)

val symbolLongPressMap = mapOf(
    // Common punctuation variants
    "!" to listOf("¡"),
    "?" to listOf("¿"),
    "-" to listOf("–", "—", "·"),
    "\"" to listOf("“", "”"),
    "'" to listOf("‘", "’"),
    "%" to listOf("‰"),
    "+" to listOf("±"),
    "/" to listOf("\\", "|"),
    "\\" to listOf("/", "|"),
    "|" to listOf("/", "\\"),
    "`" to listOf("~"),
    "=" to listOf("≠", "≈"),
    "<" to listOf("≤", "«"),
    ">" to listOf("≥", "»"),
    "&" to listOf("§"),
    "*" to listOf("★"),
    "(" to listOf("[", "{"),
    ")" to listOf("]"),
    "[" to listOf("{"),
    "]" to listOf("}"),
    "{" to listOf("["),
    "}" to listOf("]"),
    "~" to listOf("`"),
    "_" to listOf("—", "–"),
    "," to listOf(";", "、"),
    "." to listOf("…", ".com", ".vn"),
    ":" to listOf(";"),
    ";" to listOf(":"),
    // Currency variants
    "₫" to listOf("$", "€", "£", "¥", "₩", "¢"),
    "$" to listOf("₫", "€", "£", "¥", "₩"),
    "€" to listOf("$", "£"),
    "£" to listOf("€", "$"),
    "¥" to listOf("₩"),
    "₩" to listOf("¥"),
    "₹" to listOf("₨"),
    "₽" to listOf("₴"),
    // Math variants
    "±" to listOf("+"),
    "−" to listOf("-"),
    "×" to listOf("·"),
    "÷" to listOf("/"),
    "≠" to listOf("="),
    "≈" to listOf("~"),
    "≤" to listOf("<"),
    "≥" to listOf(">"),
    "∞" to listOf("°"),
    "√" to listOf("∛"),
    "∫" to listOf("∬"),
    "Δ" to listOf("δ"),
    // Quote variants
    "“" to listOf("\""),
    "”" to listOf("\""),
    "‘" to listOf("'"),
    "’" to listOf("'"),
    "«" to listOf("<"),
    "»" to listOf(">"),
    // Misc
    "°" to listOf("℃", "℉"),
    "℃" to listOf("℉"),
    "℉" to listOf("℃"),
    "§" to listOf("¶"),
    "©" to listOf("®", "™"),
    "®" to listOf("©"),
    "™" to listOf("©"),
    // Arrow pairs
    "↑" to listOf("↓"),
    "↓" to listOf("↑"),
    "←" to listOf("→"),
    "→" to listOf("←"),
    "…" to listOf("⋯")
)
